CREATE TABLE IF NOT EXISTS category_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  category_key VARCHAR(60) NOT NULL,
  name VARCHAR(180) NOT NULL,
  description VARCHAR(500) NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_category_item (category_key, name),
  INDEX idx_category_items_active (category_key, active, sort_order, name)
) ENGINE=InnoDB;

INSERT IGNORE INTO category_items (category_key, name, sort_order) VALUES
('GEM_TYPE','Blue Sapphire',10),('GEM_TYPE','Yellow Sapphire',20),('GEM_TYPE','Padparadscha Sapphire',30),
('GEM_TYPE','White Sapphire',40),('GEM_TYPE','Star Sapphire',50),('GEM_TYPE','Ruby',60),
('GEM_TYPE','Pink Spinel',70),('GEM_TYPE','Red Spinel',80),('GEM_TYPE','Blue Spinel',90),
('GEM_TYPE','Chrysoberyl',100),('GEM_TYPE','Cat''s Eye Chrysoberyl',110),('GEM_TYPE','Alexandrite',120),
('GEM_TYPE','Emerald',130),('GEM_TYPE','Aquamarine',140),('GEM_TYPE','Tourmaline',150),
('GEM_TYPE','Garnet',160),('GEM_TYPE','Topaz',170),('GEM_TYPE','Zircon',180),
('GEM_TYPE','Moonstone',190),('GEM_TYPE','Quartz',200),
('SHAPE','Rough',10),('SHAPE','Round',20),('SHAPE','Oval',30),('SHAPE','Cushion',40),
('SHAPE','Emerald',50),('SHAPE','Pear',60),('SHAPE','Marquise',70),('SHAPE','Princess',80),
('SHAPE','Asscher',90),('SHAPE','Radiant',100),('SHAPE','Heart',110),('SHAPE','Trillion',120),
('SHAPE','Baguette',130),('SHAPE','Kite',140),('SHAPE','Shield',150),('SHAPE','Hexagon',160),
('SHAPE','Octagon',170),('SHAPE','Cabochon',180),('SHAPE','Freeform',190),
('CUT','Rough',10),('CUT','Oval',20),('CUT','Cushion',30),('CUT','Emerald',40),('CUT','Round',50),
('COLOR','Blue',10),('COLOR','Yellow',20),('COLOR','Pink',30),('COLOR','Red',40),
('COLOR','Green',50),('COLOR','Orange',60),('COLOR','Purple',70),('COLOR','White',80),('COLOR','Colour change',90),
('TREATMENT','Not assessed',10),('TREATMENT','No treatment declared',20),
('TREATMENT','Heated · dealer disclosed',30),('TREATMENT','Oiled · dealer disclosed',40),
('TREATMENT','Fracture filled · dealer disclosed',50),
('TREATMENT','No indication of heat · laboratory report',60),
('TREATMENT','Treatment undetermined',70),('TREATMENT','Other treatment disclosed',80),
('METAL','Yellow gold',10),('METAL','White gold',20),('METAL','Rose gold',30),
('METAL','Platinum',40),('METAL','Silver',50),('METAL','Other',60),
('METAL_PURITY','24K',10),('METAL_PURITY','22K',20),('METAL_PURITY','18K',30),
('METAL_PURITY','14K',40),('METAL_PURITY','10K',50),('METAL_PURITY','925 Silver',60),
('METAL_PURITY','950 Platinum',70),('METAL_PURITY','Other',80),
('PAYMENT_METHOD','Bank transfer',10),('PAYMENT_METHOD','Cash',20),('PAYMENT_METHOD','Card',30),('PAYMENT_METHOD','Other',40);
